# Globalne poziomy logowania
handlers = java.util.logging.ConsoleHandler
.level = INFO

# Konfiguracja konsoli
java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter

# Profesjonalny format wyjścia (używany w Main.java)
java.util.logging.SimpleFormatter.format = [%1$tF %1$tT] [%4$-7s] %5$s %n